java:
  applicationPort: 8888
  environment:
    REFORM_TEAM: probate
    REFORM_SERVICE_NAME: orchestrator-service
    SERVICES_AUTH_PROVIDER_TOTP_SECRET: ${S2S_AUTH_TOTP_SECRET}
    LOG_LEVEL: DEBUG
    MAIL_JAVAMAILPROPERTIES_MAIL_SMTP_SSL_ENABLE: false
    MAIL_JAVAMAILPROPERTIES_MAIL_SMTP_AUTH: false
    SERVICES_CORECASEDATA_ENABLED: true
    MAIL_JAVAMAILPROPERTIES_SUBJECT: Probate Application
    AUTH_PROVIDER_SERVICE_CLIENT_KEY: ${S2S_AUTH_TOTP_SECRET}
    MAIL_USERNAME: ${PROBATE_SUB_MAIL_USERNAME}
    MAIL_PASSWORD: ${PROBATE_SUB_MAIL_PASSWORD}
    MAIL_HOST: ${PROBATE_SUB_MAIL_HOST}
    MAIL_PORT: ${PROBATE_SUB_MAIL_PORT}
    MAIL_JAVAMAILPROPERTIES_SENDER: "${PROBATE_SUB_MAIL_SENDER}
    MAIL_JAVAMAILPROPERTIES_RECIPIENT: ${PROBATE_SUB_MAIL_REC}
    PACT_BROKER_URL: pact-broker.platform.hmcts.net
    PACT_BROKER_PORT: 80
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
