apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE_NAME}-config
  namespace: ${NAMESPACE}
data:
  SERVICES_PERSISTENCE_BASEURL : "http://probate-persistence-service-aat.service.core-compute-aat.internal"
  SERVICES_NOTIFY_INVITEDATA_INVITELINK : "http://probate-frontend-aat.service.core-compute-aat.internal/executors/invitation/"
  SERVICES_PDF_SERVICE_URL : "http://cmc-pdf-service-aat.service.core-compute-aat.internal"
  SERVICES_AUTH_PROVIDER_BASEURL : "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
  DOCUMENT_MANAGEMENT_URL : "http://dm-store-aat.service.core-compute-aat.internal"
